### ISSUE TITLE
Wombag not downloading all articles the first time. 

### ISSUE THREAD

**Issue by karthink** [karthink/wombag#2]
> Did it download your Wallabag articles correctly, and does search work as advertised?
> 
> No, in my instance I have 89 articles and only 59 have been downloaded.
> 
> ![Captura desde 2023-12-22 21-54-39](https://github.com/karthink/wombag/assets/6677900/a4afdceb-fba1-4708-abfd-4a85f2b8ed76)
> 
> ![Captura desde 2023-12-22 21-52-37](https://github.com/karthink/wombag/assets/6677900/71f19780-bf8a-4292-b389-32e06202498e)

@hefistion Creating a new issue to track the download issue.  The fact it downloaded exactly 30 articles less than you have is a helpful clue, I'll look into it.

For now, could you do the following?

1. Open wombag (`M-x wombag`)
2. Call `wombag-sync` with a prefix argument (`C-u G`)

It will ask you for a date to sync forward from.  Enter a date older than your oldest article, something like 1990-01-01.  Does it download all 89 articles this time?

**Comment by hefistion** [comment]
>     1. Open wombag (`M-x wombag`)
> 
>     2. Call `wombag-sync` with a prefix argument (`C-u G`)
> 
> 
> It will ask you for a date to sync forward from. Enter a date older than your oldest article, something like 1990-01-01. Does it download all 89 articles this time?


The error persists, the 30 most recent posts are still missing.

I have tried to delete 5 articles in my wallabag instance and it syncs fine, now I have 54 articles.

**Comment by hefistion** [comment]
The new entries do appear after `wombag-sync`, the problem seems to be that during the first sync it does not download the first 30 posts.

**Comment by karthink** [comment]
> The new entries do appear after `wombag-sync`, the problem seems to be that during the first sync it does not download the first 30 posts.

Yeah, this is what I suspected.  It's a little work to test since I have to start with an empty DB and download all my articles (all 15,000 of them!) every time.

Now that all the articles are there, do the other problems still persist? (tags, archived articles missing etc)

**Comment by hefistion** [comment]
> Now that all the articles are there, do the other problems still persist? (tags, archived articles missing etc)

So far I have found the following problems:

- In the help (`?`) to search for articles it indicates that to search by tags it must be with `+tag` but for it to work you have to put` tag`
- The first 30 articles do not appear on the list

Everything else seems to be working well, now the archived publications are displayed (`&&`), it's ok., great job, thank you very much.

**Comment by krisbalintona** [comment]
I'd like to chime in here.

@hefistion seemed to indicated that all was well for him. On the other hand, This issue (I think) persists for me. No matter what, Wombag always shows 30 entries less than what I have, no matter the way I use `wombag-sync`. Wombag seems to retrieve all of them properly (based on the updates shown in the header line), but 30 less are shown and reported in the total count. 

Despite my attempts, I haven't been able to pinpoint the problem.

**Comment by goofansu** [comment]
In my case, it downloaded all the articles  (74 articles), and then deleted 30 articles, remaining 44 articles in the first sync.

**Comment by krisbalintona** [comment]
For some reason this is a persistent issue for me. Wombag will inconsistently not download all my entries. I did some digging and:
1. All the entries _are_ being downloaded, but some of they are immediately being deleted. The "Retrieving... X entries added" indicator communicates this.
2. The `wombag-sync` function is recursive, retrieving pages until all are retrieved. The function is recursively called via a `run-with-idle-timer`. **Calling `wombag-sync` immediately rather than via timer fixes the issue for me.** I don't know if there are any unintended side effects, but I haven't noticed any — what is the role of the idle timer? I think that the idle timer is unintentionally causing items to be deleted somehow, given that within `wombag-sync` there is a call to `wombag-db-delete`: `wombag-db-delete` is probably being called too late then deleting entries that were just added but shouldn't be deleted.

@karthink Thoughts?

**Comment by krisbalintona** [comment]
Update:

I think I found a fix. I pushed the commit to my fork here: https://github.com/krisbalintona/wombag/commit/32f87c349254abb7b53ba985b98ee9cd2911a0f6.

Seems like this is an issue with local-ids not being "in sync" with server-ids -- or something in the ballpark of that.

**Comment by jeffvalk** [comment]
> I think I found a fix. I pushed the commit to my fork here: [krisbalintona@32f87c3](https://github.com/krisbalintona/wombag/commit/32f87c349254abb7b53ba985b98ee9cd2911a0f6).
> 
> Seems like this is an issue with local-ids not being "in sync" with server-ids -- or something in the ballpark of that.

@krisbalintona You're right about about the cause, but your patch works by disabling local deletes altogether. That's better than having missing records, but still not the droids we're looking for...

**Comment by jeffvalk** [comment]
If we step through the individual response pages, the most recent 30 records are indeed returned as page 1 and inserted into the local database, but are then immediately deleted when the page 2 data is processed.

Here's what's going on:

`wombag-sync` means to query local IDs when the first page of results is returned from the server, and then pass the local ID list to the response handler for subsequent pages. It doesn't check the page number explicitly though, only whether `local-ids` is nil:

https://github.com/karthink/wombag/blob/d5e19cc55a7388aa3c158b5c19c885b61da1f63e/wombag.el#L222-L224

This creates an edge case when the local database is empty. When no local records exist, the initial query to populate `local-ids` will return nil, which is the correct value. But when the handler executes for the page 2 data, `local-ids` being nil causes the query to be run a second time. This query returns the IDs inserted from page 1, which makes the value of `local-ids` incorrect. These IDs create a delta and are therefore deleted from the local database.

**Comment by jeffvalk** [comment]
I created a [patch] for this...

But while I was at it, I figured I'd implement deleted entry sweeping so we have full synchronization. I [opened a PR][pr] for this.


[patch]: https://github.com/jeffvalk/wombag/commit/6ce6036d4f2b0d3e08f14b53b7722e1b374c73e9
[pr]: https://github.com/karthink/wombag/pull/7

**Comment by karthink** [comment]
I think this is fixed by @jeffvalk's PR, although I haven't tested it yet.  Closing as completed, but please reopen if the bug persists.
